### ISSUE TITLE
Support for fx:include

### ISSUE THREAD

**Issue by vigoo** [vigoo/scalafxml#20]
http://docs.oracle.com/javafx/2/api/javafx/fxml/doc-files/introduction_to_fxml.html#nested_controllers

**Comment by ptxmac** [comment]
Any progress on this? It would be awesome to just add a `private val controller: MyController` to the constructor of the parent controller

**Comment by vigoo** [comment]
Sorry I completely forgot this request. I'll try to allocate some time in the near future to look into it.

**Comment by vigoo** [comment]
Finally I managed to implement this, it needs an extra annotation. See the example code in the above commit. Will publish the new version soon.
