### ISSUE TITLE
Bump MacWire version for dependency resolver

### ISSUE THREAD

**Issue by mikolak-net** [vigoo/scalafxml#21]
While it's great that there's a MacWire resolver provided now, the version used is pretty old - `1.0.7` vs the `2.2.4` current. In the meantime, there had been e.g. package renamings, which makes usage in `scalafxml` a pretty jarring experience.

Any specific reason why `1.0.7` was chosen?

**Comment by vigoo** [comment]
There is no other specific reason than it was the latest when I added this :)

**Comment by vigoo** [comment]
Released a new version of scalafxml (0.3)

**Comment by mikolak-net** [comment]
Great to hear that - thanks :)!
